/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadoraproposiciones;

import javax.swing.JOptionPane;



/**
 *
 * @author PROFESIONAL
 */
public class calculadora extends javax.swing.JFrame {
    String str="";
    int operadores=0;
    int parentesis=0;
    int hechos=0;
    /**
     * Creates new form calculadora
     */
    public calculadora() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pantalla = new javax.swing.JLabel();
        c = new javax.swing.JButton();
        del = new javax.swing.JButton();
        igual = new javax.swing.JButton();
        p = new javax.swing.JButton();
        q = new javax.swing.JButton();
        r = new javax.swing.JButton();
        s = new javax.swing.JButton();
        negacion = new javax.swing.JButton();
        conjuncion = new javax.swing.JButton();
        disyuccion = new javax.swing.JButton();
        implicacion = new javax.swing.JButton();
        dobleImplicacion = new javax.swing.JButton();
        parentesisA = new javax.swing.JButton();
        parentesisC = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 204));

        pantalla.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        pantalla.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 204)));
        pantalla.setOpaque(true);

        c.setText("C");
        c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cActionPerformed(evt);
            }
        });

        del.setText("DEL");
        del.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delActionPerformed(evt);
            }
        });

        igual.setText("=");
        igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualActionPerformed(evt);
            }
        });

        p.setText("P");
        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });

        q.setText("Q");
        q.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qActionPerformed(evt);
            }
        });

        r.setText("R");
        r.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rActionPerformed(evt);
            }
        });

        s.setText("S");
        s.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sActionPerformed(evt);
            }
        });

        negacion.setText("~");
        negacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                negacionActionPerformed(evt);
            }
        });

        conjuncion.setText("^");
        conjuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conjuncionActionPerformed(evt);
            }
        });

        disyuccion.setText("v");
        disyuccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                disyuccionActionPerformed(evt);
            }
        });

        implicacion.setText("->");
        implicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                implicacionActionPerformed(evt);
            }
        });

        dobleImplicacion.setText("<->");
        dobleImplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dobleImplicacionActionPerformed(evt);
            }
        });

        parentesisA.setText("(");
        parentesisA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisAActionPerformed(evt);
            }
        });

        parentesisC.setText(")");
        parentesisC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentesisCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(c, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                                .addComponent(r, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(parentesisA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(p, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(q, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parentesisC, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(s, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(del))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(disyuccion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(conjuncion, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(dobleImplicacion)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(negacion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(implicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(40, 40, 40))
                            .addComponent(igual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(disyuccion)
                            .addComponent(conjuncion)
                            .addComponent(parentesisA)
                            .addComponent(parentesisC))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(negacion)
                            .addComponent(implicacion))
                        .addGap(18, 18, 18)
                        .addComponent(dobleImplicacion)
                        .addGap(18, 18, 18)
                        .addComponent(igual, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(p)
                            .addComponent(q))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(r)
                            .addComponent(s))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(c)
                            .addComponent(del))))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void negacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_negacionActionPerformed
        pantalla.setText(pantalla.getText()+"~");
    }//GEN-LAST:event_negacionActionPerformed

    private void conjuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conjuncionActionPerformed
        pantalla.setText(pantalla.getText()+"^");
    }//GEN-LAST:event_conjuncionActionPerformed

    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        pantalla.setText(pantalla.getText()+"p");
    }//GEN-LAST:event_pActionPerformed

    private void qActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qActionPerformed
        pantalla.setText(pantalla.getText()+"q");
    }//GEN-LAST:event_qActionPerformed

    private void rActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rActionPerformed
        pantalla.setText(pantalla.getText()+"r");        
    }//GEN-LAST:event_rActionPerformed

    private void sActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sActionPerformed
        pantalla.setText(pantalla.getText()+"s");
    }//GEN-LAST:event_sActionPerformed

    private void disyuccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_disyuccionActionPerformed
        pantalla.setText(pantalla.getText()+"v");
    }//GEN-LAST:event_disyuccionActionPerformed

    private void implicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_implicacionActionPerformed
        pantalla.setText(pantalla.getText()+"->");
    }//GEN-LAST:event_implicacionActionPerformed

    private void dobleImplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dobleImplicacionActionPerformed
        pantalla.setText(pantalla.getText()+"<->");
    }//GEN-LAST:event_dobleImplicacionActionPerformed

    private void parentesisAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisAActionPerformed
        pantalla.setText(pantalla.getText()+"(");
    }//GEN-LAST:event_parentesisAActionPerformed

    private void parentesisCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentesisCActionPerformed
        pantalla.setText(pantalla.getText()+")");
    }//GEN-LAST:event_parentesisCActionPerformed

    private void cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cActionPerformed
       pantalla.setText("");
    }//GEN-LAST:event_cActionPerformed

    private void delActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delActionPerformed
       str= pantalla.getText();
       str=str.substring(0, str.length()-1);
       pantalla.setText(str);
    }//GEN-LAST:event_delActionPerformed

    private void igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualActionPerformed
        str= pantalla.getText();
        int parentesisAbiertos=0;
        int parentesisCerrados=0;
//recorremos el arreglo en busqueda de los caracteres
        for (int i = 0; i < str.length(); i++) {
            char caracter=str.charAt(i);
//buscamos los caracteres que representan hechos y si se encuentran seguidos de otro hecho
            if(caracter=='p'||caracter=='q'||caracter=='r'||caracter=='s'){
                if(str.charAt(i+1)=='p'||str.charAt(i+1)=='q'||str.charAt(i+1)=='r'||str.charAt(i+1)=='s'){
                    JOptionPane.showMessageDialog(null,"Error de Sintaxis");
                    System.exit(0);
                }else{
                    hechos++;
                }
                            
            }
//contamos los parentesis 
            if(caracter=='('||caracter==')'){
                if(caracter=='('){
                    parentesisAbiertos++;
                }else{
                    parentesisCerrados++;
                }    
            }
// contamos operadores
            if(caracter=='v'||caracter=='^'||caracter=='~'){
                operadores++;            
            }
            if(caracter=='<'&& str.charAt(i+1)=='-'&& str.charAt(i+2)=='>'){
                operadores++;
            }
            if(caracter=='-'&& str.charAt(i+1)=='>'&& str.charAt(i-1)!='<'){
                operadores++;
            }
        }
        if(parentesisAbiertos==parentesisCerrados){
            int suma=parentesisAbiertos+parentesisCerrados;
            JOptionPane.showMessageDialog(null, "\n Numero de hechos: "+hechos+"\n Numero de operadores: "+operadores+"\n Numero de parentesis: "+suma);
        }else{
            JOptionPane.showMessageDialog(null,"No todos los parentesis se encuentran emparejados");
        }
        operadores=0;
        parentesis=0;
        hechos=0;
        		
    }//GEN-LAST:event_igualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton c;
    private javax.swing.JButton conjuncion;
    private javax.swing.JButton del;
    private javax.swing.JButton disyuccion;
    private javax.swing.JButton dobleImplicacion;
    private javax.swing.JButton igual;
    private javax.swing.JButton implicacion;
    private javax.swing.JButton negacion;
    private javax.swing.JButton p;
    private javax.swing.JLabel pantalla;
    private javax.swing.JButton parentesisA;
    private javax.swing.JButton parentesisC;
    private javax.swing.JButton q;
    private javax.swing.JButton r;
    private javax.swing.JButton s;
    // End of variables declaration//GEN-END:variables
}
